apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  selector:
    app: invoice-service
  ports:
  - port: 3010
    targetPort: 3010
