apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  selector:
    app: recommendation-service
  ports:
  - port: 3013
    targetPort: 3013
