apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  selector:
    app: wishlist-service
  ports:
  - port: 3007
    targetPort: 3007
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service-preview
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: wishlist-service
  ports:
  - port: 80
    targetPort: 3007
  type: ClusterIP
